name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: |
        docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/my-portfolio-v2:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/my-portfolio-v2:latest
